# Header
menu:
  Home: /
  Java Tutorials: /java
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: bottom
widgets:
#- category
#- tag
#- tagcloud
- archive
#- recent_posts

# widget behavior
archive_type: 'yearly'
show_count: false

# Miscellaneous
google_analytics: UA-599349-1
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
